"""
TurboQuant / RaBitQ vector quantization for ANN search
"""
from __future__ import annotations
import collections.abc
import numpy
import numpy.typing
import typing
__all__: list[str] = ['RaBitQFastScan', 'RaBitQSpace', 'TurboQuantFastScan', 'TurboQuantSpace', 'detected_isa']
class RaBitQFastScan:
    """
    Two-stage FastScan search over RaBitQ codes (built from vectors).
    """
    def __init__(self, space: RaBitQSpace, X: collections.abc.Buffer, eps0: typing.SupportsFloat | typing.SupportsIndex = 1.899999976158142) -> None:
        ...
    def __len__(self) -> int:
        ...
    def codes(self) -> numpy.typing.NDArray[numpy.uint8]:
        ...
    def scan(self, query: collections.abc.Buffer) -> tuple[numpy.typing.NDArray[numpy.float32], numpy.typing.NDArray[numpy.float32]]:
        """
        (stage-1 estimate, lower bound) for every code.
        """
    def search(self, query: collections.abc.Buffer, k: typing.SupportsInt | typing.SupportsIndex) -> tuple[numpy.typing.NDArray[numpy.uint32], numpy.typing.NDArray[numpy.float32], int]:
        """
        (ids, dists, n_refined): two-stage search; n_refined codes used the full code.
        """
class RaBitQSpace:
    def __init__(self, dim: typing.SupportsInt | typing.SupportsIndex, rot_seed: typing.SupportsInt | typing.SupportsIndex = 42, centroid: typing.Any = None, bits: typing.SupportsInt | typing.SupportsIndex = 1, encode_mode: typing.Any = None, *, rotation: str = 'kac', rotation_rounds: typing.SupportsInt | typing.SupportsIndex = 3, query_bits: typing.Any = None, num_threads: typing.SupportsInt | typing.SupportsIndex = 0, isa: str = 'auto') -> None:
        ...
    def bits(self) -> int:
        ...
    def centroid(self) -> numpy.typing.NDArray[numpy.float32]:
        ...
    def code_size_bytes(self) -> int:
        ...
    def dim(self) -> int:
        ...
    def distance(self, query: collections.abc.Buffer, code: collections.abc.Buffer) -> float:
        ...
    def distance_1_to_n(self, query: collections.abc.Buffer, codes: collections.abc.Buffer) -> numpy.typing.NDArray[numpy.float32]:
        ...
    def distance_bound(self, query: collections.abc.Buffer, code: collections.abc.Buffer, eps0: typing.SupportsFloat | typing.SupportsIndex = 1.899999976158142) -> tuple[float, float, float]:
        """
        (estimate, lower, upper) of the squared distance from the RaBitQ error bound.
        """
    def distance_kernel(self) -> str:
        ...
    def distance_m_to_n(self, queries: collections.abc.Buffer, codes: collections.abc.Buffer) -> numpy.typing.NDArray[numpy.float32]:
        ...
    def distance_scalar(self, query: collections.abc.Buffer, code: collections.abc.Buffer) -> float:
        ...
    def encode(self, x: collections.abc.Buffer) -> numpy.typing.NDArray[numpy.uint8]:
        ...
    def encode_batch(self, X: collections.abc.Buffer) -> numpy.typing.NDArray[numpy.uint8]:
        ...
    def encode_batch_into(self, X: collections.abc.Buffer, out: collections.abc.Buffer) -> None:
        ...
    def encode_into(self, x: collections.abc.Buffer, out: collections.abc.Buffer) -> None:
        ...
    def encode_mode(self) -> str:
        ...
    def fixed_scale(self) -> float:
        ...
    def padded_dim(self) -> int:
        ...
    def query_bits(self) -> int:
        ...
    def query_size_bytes(self) -> int:
        ...
    def rotation(self) -> str:
        ...
    def train(self, X: collections.abc.Buffer) -> None:
        """
        Fit to X [n, dim] float32: centroid = mean(X); trained_scale also calibrates its scale on the residuals. Re-encode codes written before.
        """
    def trained(self) -> bool:
        ...
class TurboQuantFastScan:
    """
    FastScan flat index over 4-bit TurboQuantSpace codes.
    """
    def __init__(self, space: TurboQuantSpace, codes: collections.abc.Buffer) -> None:
        ...
    def __len__(self) -> int:
        ...
    def scan(self, query: collections.abc.Buffer) -> numpy.typing.NDArray[numpy.float32]:
        """
        Approximate (LUT-quantized) distances to every code.
        """
    def search(self, query: collections.abc.Buffer, k: typing.SupportsInt | typing.SupportsIndex, rerank: typing.SupportsInt | typing.SupportsIndex = 4) -> tuple[numpy.typing.NDArray[numpy.uint32], numpy.typing.NDArray[numpy.float32]]:
        """
        (ids, dists) of the k nearest codes; k * rerank candidates are re-scored.
        """
class TurboQuantSpace:
    """
    TurboQuant code format v2 (see include/turboquant/space.h).
    """
    @staticmethod
    def format_version() -> int:
        ...
    def __getstate__(self) -> tuple[bytes, int]:
        ...
    def __init__(self, dim: typing.SupportsInt | typing.SupportsIndex, bits: typing.SupportsInt | typing.SupportsIndex = 4, *, qjl: bool = False, estimator: str = 'corrected', qjl_cross: str = 'linear', centering: str = 'ivf', n_clusters: typing.SupportsInt | typing.SupportsIndex = 256, rotation_rounds: typing.SupportsInt | typing.SupportsIndex = 3, rot_seed: typing.SupportsInt | typing.SupportsIndex = 42, qjl_seed: typing.SupportsInt | typing.SupportsIndex = 137, num_threads: typing.SupportsInt | typing.SupportsIndex = 0, isa: str = 'auto') -> None:
        ...
    def __setstate__(self, arg0: tuple) -> None:
        ...
    def bits(self) -> int:
        ...
    def centering(self) -> str:
        ...
    def centroids(self) -> numpy.typing.NDArray[numpy.float32]:
        ...
    def code_size_bytes(self) -> int:
        ...
    def decode(self, code: collections.abc.Buffer) -> numpy.typing.NDArray[numpy.float32]:
        """
        Approximate reconstruction of the encoded vector.
        """
    def dim(self) -> int:
        ...
    def distance(self, query: collections.abc.Buffer, code: collections.abc.Buffer) -> float:
        ...
    def distance_1_to_n(self, query: collections.abc.Buffer, codes: collections.abc.Buffer) -> numpy.typing.NDArray[numpy.float32]:
        ...
    def distance_m_to_n(self, queries: collections.abc.Buffer, codes: collections.abc.Buffer) -> numpy.typing.NDArray[numpy.float32]:
        ...
    def distance_m_to_n_symmetric(self, codes_a: collections.abc.Buffer, codes_b: collections.abc.Buffer) -> numpy.typing.NDArray[numpy.float32]:
        ...
    def distance_m_to_n_symmetric_full(self, codes_a: collections.abc.Buffer, codes_b: collections.abc.Buffer) -> numpy.typing.NDArray[numpy.float32]:
        ...
    def distance_symmetric(self, code_a: collections.abc.Buffer, code_b: collections.abc.Buffer) -> float:
        ...
    def distance_symmetric_full(self, code_a: collections.abc.Buffer, code_b: collections.abc.Buffer) -> float:
        ...
    def encode(self, x: collections.abc.Buffer) -> numpy.typing.NDArray[numpy.uint8]:
        ...
    def encode_batch(self, X: collections.abc.Buffer) -> numpy.typing.NDArray[numpy.uint8]:
        ...
    def encode_batch_into(self, X: collections.abc.Buffer, out: collections.abc.Buffer) -> None:
        ...
    def encode_into(self, x: collections.abc.Buffer, out: collections.abc.Buffer) -> None:
        ...
    def kernel_isa(self) -> str:
        ...
    def n_clusters(self) -> int:
        ...
    def num_threads(self) -> int:
        ...
    def padded_dim(self) -> int:
        ...
    def qjl(self) -> bool:
        ...
    def rotation_rounds(self) -> int:
        ...
    def set_centroids(self, centroids: collections.abc.Buffer) -> None:
        ...
    def train(self, X: collections.abc.Buffer, seed: typing.SupportsInt | typing.SupportsIndex = 1234, iters: typing.SupportsInt | typing.SupportsIndex = 10) -> None:
        """
        Fit the centering (mean or k-means centroids) on X [n, dim].
        """
    def trained(self) -> bool:
        ...
def detected_isa() -> str:
    """
    Kernel family this CPU/build dispatches to: 'avx2', 'neon' or 'scalar'.
    """
