"""
TurboQuant — SIMD-accelerated 4/8-bit quantization for ANN
"""
from __future__ import annotations
import collections.abc
import numpy
import numpy.typing
import typing
__all__: list[str] = ['PreparedQuery', 'TurboQuantSpace']
class PreparedQuery:
    pass
class TurboQuantSpace:
    def __init__(self, dim: typing.SupportsInt | typing.SupportsIndex, bits_per_coord: typing.SupportsInt | typing.SupportsIndex = 4, rot_seed: typing.SupportsInt | typing.SupportsIndex = 42, qjl_seed: typing.SupportsInt | typing.SupportsIndex = 137) -> None:
        ...
    def bits_per_coord(self) -> int:
        ...
    def code_size_bytes(self) -> int:
        ...
    def dim(self) -> int:
        ...
    def distance(self, query: collections.abc.Buffer, code: collections.abc.Buffer) -> float:
        ...
    def distance_1_to_n(self, query: collections.abc.Buffer, codes: collections.abc.Buffer) -> numpy.typing.NDArray[numpy.float32]:
        ...
    def distance_m_to_n(self, queries: collections.abc.Buffer, codes: collections.abc.Buffer) -> numpy.typing.NDArray[numpy.float32]:
        ...
    def distance_m_to_n_symmetric(self, codes_a: collections.abc.Buffer, codes_b: collections.abc.Buffer) -> numpy.typing.NDArray[numpy.float32]:
        ...
    def distance_symmetric(self, code_a: collections.abc.Buffer, code_b: collections.abc.Buffer) -> float:
        ...
    def encode(self, x: collections.abc.Buffer) -> numpy.typing.NDArray[numpy.uint8]:
        ...
    def encode_batch(self, X: collections.abc.Buffer) -> numpy.typing.NDArray[numpy.uint8]:
        ...
    def encode_batch_into(self, X: collections.abc.Buffer, out: collections.abc.Buffer) -> None:
        ...
    def encode_into(self, x: collections.abc.Buffer, out: collections.abc.Buffer) -> None:
        ...
    def prepare_query(self, query: collections.abc.Buffer) -> PreparedQuery:
        ...
